# Generated by Django 2.2.3 on 2019-08-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190731_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='conversation_id',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='sender_id',
        ),
        migrations.DeleteModel(
            name='Conversations',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
