# Generated by Django 2.2.3 on 2019-08-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190804_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='123qwe!@#', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='alaki', max_length=30),
            preserve_default=False,
        ),
    ]
