# Generated by Django 2.2.3 on 2019-08-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190811_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.IntegerField(null=True),
        ),
    ]
