# Generated by Django 2.2.3 on 2019-08-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190814_1306'),
        ('users', '0011_auto_20190814_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
