# Generated by Django 2.2.3 on 2019-07-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='number_of_friends',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
