# Generated by Django 2.2.3 on 2019-07-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190731_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='members',
            field=models.ManyToManyField(to='users.Users'),
        ),
        migrations.DeleteModel(
            name='ConversationMembers',
        ),
    ]
